# Generated by Django 5.2.7 on 2025-10-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movieName", models.CharField(max_length=255)),
                ("directorName", models.CharField(max_length=255)),
            ],
        ),
    ]
